abstract final class ForjaQuotes {
  static const list = [
    'A disciplina é a ponte entre objetivos e conquistas.',
    'Você não é suas tentações. Você é sua resposta a elas.',
    'Cada dia limpo é um tijolo na construção de quem você quer ser.',
    'A forja aquece para endurecer, não para destruir.',
    'Força não é ausência de fraqueza. É escolher não ceder.',
    'O homem que controla seus impulsos controla seu destino.',
    'Sua mente é o campo de batalha. Cada vitória importa.',
    'O passado não define. A escolha de hoje define.',
    'Construa quem você quer ser, dia por dia, bloco por bloco.',
    'O caminho é difícil porque vale a pena.',
    'Não existe atalho para uma vida que você respeita.',
    'A tentação passa. O orgulho de resistir permanece.',
    'Você está forjando sua melhor versão. Não abandone o processo.',
    'O aço só fica forte depois do fogo.',
    'Resista hoje para ser livre amanhã.',
    'Cada manhã é uma nova chance de ser quem você decidiu ser.',
    'A disciplina que você pratica hoje é a liberdade que você conquista amanhã.',
    'Não é sobre ser perfeito. É sobre continuar.',
    'Quando a vontade fraqueja, lembre do porquê você começou.',
    'Você é mais forte do que a menor versão de si mesmo.',
    'O guerreiro não foge da batalha. Ele se prepara para ela.',
    'Cada recaída que você evitou é uma vitória silenciosa.',
    'A forja não tem dias fáceis. Só tem dias que valeram a pena.',
    'Seu futuro eu vai agradecer pela escolha que você fizer agora.',
    'A clareza mental é o prêmio de quem mantém a disciplina.',
    'Não é sobre não ter vontade. É sobre ser maior do que ela.',
    'O homem que domina a si mesmo domina qualquer coisa.',
    'Pequenas vitórias constroem grandes caracteres.',
    'Hoje você escolhe quem será amanhã.',
    'A jornada é longa. Mas você foi feito para isso.',
  ];
}
